"""TASK D — Performance Outsourcing Decision Engine: 12 mandatory layers x 8 attributes, gate mapping, BTS requirements matrix.
Structure only (roles, not names; no company data; no synthetic financial numbers used as evidence)."""
import csv
A = ["layer","input","calculation_or_judgment","owner_role","evidence_required","green_amber_red","failure_mode","data_requirement","bts_capability_required"]
L = [
["1 SYSTEM BOUNDARY","Asset register, process units, interfaces, third parties, decision rights map","Judgment: define in-scope assets/processes/decisions; list exogenous drivers explicitly","Opportunity owner (role) with client counterpart","Signed boundary document; RACI for decisions; list of exogenous factors","GREEN: all outcome KPIs map to in-boundary drivers; AMBER: <20 % of KPI variance from exogenous drivers unmodelled; RED: boundary disputed or undocumented","Scope creep; blame-shifting on exogenous events","Asset hierarchy (ISO 14224 style), criticality classes, interface list","Asset hierarchy & criticality master data"],
["2 BASELINE / COUNTERFACTUAL","≥24 months history: availability, production counts, WO backlog with criticality, opex, events, load/mix","Calculation: normalise to load & product mix; estimate baseline noise (σ) and trend; define counterfactual (as-is trajectory incl. ageing)","Feasibility lead (role); independent verifier (role)","Frozen baseline dataset with hash; normalisation method note; σ estimate","GREEN: σ_baseline < 0.5 × expected effect; AMBER: 0.5–1×; RED: >1× or <24 months data","Improvement indistinguishable from noise; regression-to-mean claimed as gain","Historian/DCS time series, CMMS WOs, ERP cost, production accounting","Time-series storage, WO history with criticality, cost-object mapping"],
["3 CONTROLLABILITY MATRIX","Each outcome promise decomposed into drivers","Judgment+calc: classify each driver Bilfinger-controls / joint / client-decides / external; weight by sensitivity from model","Feasibility lead (role); approved by regional P&L owner (role)","Matrix with sensitivities; client sign-off on decision rights","GREEN: >60 % of KPI sensitivity in Bilfinger/joint control with defined escalation; AMBER: 40–60 %; RED: <40 % or client decision lag unbounded","Accepting responsibility without authority (capex, operating mode)","Sensitivity outputs of the state model; decision-lag statistics","Scenario/sensitivity tooling (may be offline model)"],
["4 HSEQ / ASSET-INTEGRITY RED LINES","Regulatory obligations, safety-critical element list, inspection due dates, MOC backlog","Judgment (human approval): define binding constraints; not tradeable against value","HSEQ / integrity function (role), independent of site P&L","Red-line register; inspection compliance status; screening for refining/oil&gas/chemicals","GREEN: zero overdue safety-critical inspections and MOCs; AMBER: overdue with approved deviation; RED: any unapproved overdue or red-line breach","Latent integrity debt hidden by KPI focus on availability","Inspection plans, SCE list, deviation records","Integrity management module or interface (IDMS/RBI)"],
["5 TRANSITION READINESS","Personnel transfer list, competence matrix, data access plan, contract Day-1 checklist","Judgment+calc: readiness score; expected efficiency dip and duration","Transition manager (role)","Competence coverage ≥ criticality needs; data feeds tested; Day-1 plan","GREEN: critical competence covered ≥90 %, data live before Day 1; AMBER: 75–90 %; RED: <75 % or data access not contracted","Transition dip longer than planned erodes value (prototype: transition_delay turned value negative)","Skills matrix, vacancies, system access inventory","Identity/access, skills matrix, mobile WO execution"],
["6 VALUE CREATION MODEL","Baseline, controllability, cost plan, contribution margin, demand limit","Calculation: JOINT VALUE = ΔPV(margin, demand-limited) + ΔPV(resource savings) − PV(transition/dev) − ΔPV(expected residual loss); no double counting","Feasibility lead (role); finance review (role)","Model file, assumptions register, unit checks, no double-count check","GREEN: P50 > 0 with documented drivers; AMBER: P50 > 0 but driver concentration >70 % in one lever; RED: P50 ≤ 0","Lost production valued at sales price; availability above demand counted","Contribution margin per hour, demand plan, cost objects","Cost & production data integration"],
["7 VALUE-AT-RISK / P10","Value model + uncertainty (θ priors, shock scenarios)","Calculation: Monte Carlo / scenario; P10, P(joint<0); stress: deferral, latent debt, capex delay, skills, data, demand, transition, gaming, end-of-term","Feasibility lead (role); risk function (role)","Distribution, stress table, sensitivity ranking","GREEN: P10 > 0; AMBER: P10 < 0 but P(joint<0) < 20 % and mitigations costed; RED: P(joint<0) ≥ 30 %","Deciding on P50 only (prototype: P50 +, P10 − under synthetic params)","Same as layer 6 + shock scenario library","Scenario tooling"],
["8 BENEFIT ATTRIBUTION","Measured KPIs, baseline, exogenous drivers, intervention log","Calculation: normalised before/after; causal estimate (DiD/synthetic control) ONLY if parallel-trend assumption verified in pre-period; else descriptive","Independent verifier (role)","Attribution report with uncertainty; assumption checks","GREEN: effect > 2σ and attribution assumptions verified; AMBER: effect > 2σ, assumptions unverified; RED: effect < 2σ","Attributing market/load effects to the service","Intervention log with timestamps; exogenous covariates","Event/intervention logging"],
["9 KPI ANTI-GAMING CONTROLS","KPI definitions with data lineage; two independent sources per outcome KPI","Calculation: cross-check reported KPI vs independent source (e.g. availability vs production counts); backlog age profile; WO closure audit sample","Independent verifier (role); internal audit (role)","Reconciliation report; audit sample results","GREEN: reported−independent within 2σ of noise; AMBER: 2–3σ; RED: >3σ or definitional changes without approval","Reported availability inflates gain-share; criticality re-coding; administrative WO closures","Two-source KPI pipelines; WO audit trail","Immutable audit trail, lineage, reconciliation"],
["10 CUSTOMER/BILFINGER VALUE SPLIT","Joint value distribution; fee structure (fixed, gain-share, penalties)","Calculation: client and provider cash flows separately; identity client + provider = joint; incentive test under cost-cutting policy","Contract lead (role); finance (role)","Cash-flow model both sides; incentive stress result","GREEN: both parties P50 > 0 AND provider does not gain under a deferral policy; AMBER: one side ≤ 0 at P10; RED: provider gains under deferral (prototype found this with fixed fee ≥ delivery cost)","Fixed fee above delivery cost rewards deferral; gain-share on unverified KPI","Fee terms, delivery cost plan","Contract/fee calculation with verified KPI inputs"],
["11 CONTINUOUS VALIDATION","Monthly measured KPIs, integrity indicator, competence index, backlog age, cost","Calculation: value path vs P10/P50 bands; drift tests; quarterly independent verification; BTS gap review","Site lead (role); client steering committee (roles)","Monthly value report with bands; quarterly verification","GREEN: within P50 band, integrity GREEN; AMBER: below P50 one quarter; RED: below P10 two consecutive quarters or KPI drift vs independent source","Green dashboards from filled forms; late detection of debt","Layer 9 pipelines; model re-estimation","Dashboarding with band logic; alerting"],
["12 RENEWAL / EXIT CONSEQUENCES","Handback condition audit, residual integrity debt, backlog age, competence at exit","Judgment+calc: compare handback vs contract; end-of-term deferral test (last 12 months effort vs plan)","Contract lead (role); HSEQ/integrity (role)","Handback audit; effort profile; sanctions/bonuses applied","GREEN: handback ≥ contract and effort profile flat; AMBER: minor deviations remedied; RED: residual debt above contract or effort drop >20 % in final year","End-of-contract deferral (prototype: P1 defers in final year)","Condition audit data, effort logs","Condition assessment records, effort tracking"],
]
with open("results/po_decision_engine_layers.csv","w",newline="") as f: csv.writer(f).writerow(A); csv.writer(f).writerows(L)
G = [["gate","layers_required_to_be_GREEN_or_AMBER","hard_stop_if_RED","decision_output"],
["Qualification","1, 3 (preliminary), 4 (screening)","1, 4","Go/no-go to feasibility; boundary charter"],
["Feasibility","1, 2, 3, 4, 5, 6, 7","2, 3, 4, 7","Value case with P10; pilot design; controllability sign-off"],
["Due Diligence","2 (frozen), 4 (detailed), 5, 6 (updated), 10","4, 10","Contract term sheet; red-line register"],
["Contracting","3 (decision rights in contract), 8 (attribution method), 9 (KPI lineage), 10, 12 (handback terms)","9, 10, 12","Signed contract with verifiable KPIs and incentive test passed"],
["Transition / Day 1","5, 9 (pipelines live), 2 (baseline signed)","5","Day-1 release; value tracking starts"],
["Operate & Improve","8, 9, 11, 4 (continuous)","4, 11 (RED two quarters)","Corrective plan / re-baselining / exit trigger"],
["Renewal / Exit","12, 8 (final attribution), 2 (new baseline)","12","Renew, re-scope, or exit with handback settlement"]]
with open("results/po_gate_mapping.csv","w",newline="") as f: csv.writer(f).writerows(G)
B = [["requirement","source_layer","must_have_for_performance_model","Improve BTS (configure/discipline)","BTS + Intelligence Layer","Replace BTS","decision_data_needed"],
["Asset hierarchy & criticality master data","1,3","yes","Typically achievable if fields exist and governance enforced","Not needed for this requirement","Only if master data model cannot represent criticality","Field inventory; data quality audit of criticality coding"],
["Time-series + WO + cost integration for baseline","2,6","yes","Depends on existing interfaces","Layer can integrate read-only sources","If no interfaces feasible","Integration inventory; historian access"],
["Sensitivity/scenario modelling (P10)","3,7","yes","Offline model acceptable","Natural fit (model sits in layer)","Not required","Modelling skills; assumption register process"],
["Integrity red-line tracking (SCE inspections, MOC)","4","yes (refining/O&G/chem)","If IDMS/RBI module exists","Layer can aggregate from IDMS","If no IDMS and none attachable","SCE list coverage; inspection data location"],
["Skills matrix & access management","5","yes","Usually configurable","Not needed","Not required","HR system fields"],
["Two-source KPI reconciliation + immutable audit trail","9,11","yes","Rarely native; audit trail often weak","Core layer capability","If audit trail cannot be enforced at source","Audit-trail capability test; production-count access"],
["Intervention log & attribution analytics","8","yes","Partial (WO notes)","Core layer capability","Not required","Event logging practice"],
["Fee/gain-share calculation from verified KPIs","10","yes","Spreadsheet acceptable if inputs verified","Layer can automate with lineage","Not required","Contract formula; KPI lineage"],
["Value-band dashboards with alerting","11","yes","BI on top of BTS possible","Core layer capability","Not required","BI tooling; band logic"],
["Handback condition & effort tracking","12","yes","WO/effort data usually present","Aggregation only","Not required","Effort logging discipline"]]
with open("results/po_bts_requirements.csv","w",newline="") as f: csv.writer(f).writerows(B)
print("written po_decision_engine_layers.csv, po_gate_mapping.csv, po_bts_requirements.csv")
